
/* Drop Tables */

DROP TABLE ACCOUNT_INTRODUCE CASCADE CONSTRAINTS;
DROP TABLE BOARD_REPLY CASCADE CONSTRAINTS;
DROP TABLE BOARD_COMMENT CASCADE CONSTRAINTS;
DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE FBOARD_COMMENT CASCADE CONSTRAINTS;
DROP TABLE FBOARD CASCADE CONSTRAINTS;
DROP TABLE ACCOUNT CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE ACCOUNT
(
	ID nvarchar2(15) NOT NULL,
	PASSWORD nvarchar2(20) NOT NULL,
	EMAIL nvarchar2(30) NOT NULL UNIQUE,
	NAME nvarchar2(15) NOT NULL,
	BIRTHDAY nvarchar2(50) DEFAULT '1900[Year] 1[Month] 3[Day]' NOT NULL,
	GENDER nvarchar2(10) DEFAULT 'M' NOT NULL,
	EDUCATION char(1 char) DEFAULT 'E' NOT NULL,
	HOBBY nvarchar2(50),
	JOINDATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE ACCOUNT_INTRODUCE
(
	INO number NOT NULL,
	ID nvarchar2(15) NOT NULL,
	PNUMBER nvarchar2(20) DEFAULT '',
	INTRODUCE nvarchar2(500) DEFAULT '',
	PRIMARY KEY (INO)
);


CREATE TABLE BOARD
(
	BNO number NOT NULL,
	TITLE nvarchar2(100) NOT NULL,
	POSTDATE date DEFAULT SYSDATE NOT NULL,
	HITCOUNT number DEFAULT 0 NOT NULL,
	LIKECOUNT number DEFAULT 0 NOT NULL,
	CONTENT nvarchar2(2000) NOT NULL,
	ID nvarchar2(15) NOT NULL,
	PRIMARY KEY (BNO)
);


CREATE TABLE BOARD_COMMENT
(
	CNO number NOT NULL,
	BNO number NOT NULL,
	ID nvarchar2(15) NOT NULL,
	BCOMMENT nvarchar2(100) NOT NULL,
	POSTDATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (CNO)
);


CREATE TABLE BOARD_REPLY
(
	RNO number NOT NULL,
	CNO number NOT NULL,
	ID nvarchar2(15) NOT NULL,
	BREPLY nvarchar2(100),
	POSTDATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (RNO)
);


CREATE TABLE FBOARD
(
	FNO number NOT NULL,
	TITLE nvarchar2(100) NOT NULL,
	POSTDATE date DEFAULT SYSDATE NOT NULL,
	HITCOUNT number DEFAULT 0 NOT NULL,
	LIKECOUNT number DEFAULT 0 NOT NULL,
	CONTENT nvarchar2(2000) NOT NULL,
	ID nvarchar2(15) NOT NULL,
	PRIMARY KEY (FNO)
);


CREATE TABLE FBOARD_COMMENT
(
	FCNO number NOT NULL,
	FNO number NOT NULL,
	ID nvarchar2(15) NOT NULL,
	FCOMMENT nvarchar2(100) NOT NULL,
	POSTDATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (FCNO)
);



/* Create Foreign Keys */

ALTER TABLE ACCOUNT_INTRODUCE
	ADD FOREIGN KEY (ID)
	REFERENCES ACCOUNT (ID)
;


ALTER TABLE BOARD
	ADD FOREIGN KEY (ID)
	REFERENCES ACCOUNT (ID)
;


ALTER TABLE BOARD_COMMENT
	ADD FOREIGN KEY (ID)
	REFERENCES ACCOUNT (ID)
;


ALTER TABLE BOARD_REPLY
	ADD FOREIGN KEY (ID)
	REFERENCES ACCOUNT (ID)
;


ALTER TABLE FBOARD
	ADD FOREIGN KEY (ID)
	REFERENCES ACCOUNT (ID)
;


ALTER TABLE FBOARD_COMMENT
	ADD FOREIGN KEY (ID)
	REFERENCES ACCOUNT (ID)
;


ALTER TABLE BOARD_COMMENT
	ADD FOREIGN KEY (BNO)
	REFERENCES BOARD (BNO)
;


ALTER TABLE BOARD_REPLY
	ADD FOREIGN KEY (CNO)
	REFERENCES BOARD_COMMENT (CNO)
;


ALTER TABLE FBOARD_COMMENT
	ADD FOREIGN KEY (FNO)
	REFERENCES FBOARD (FNO)
;



